from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 338)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_res = QtWidgets.QLabel(self.centralwidget)
        self.label_res.setGeometry(QtCore.QRect(0, 0, 400, 90))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_res.setFont(font)
        self.label_res.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_res.setObjectName("label_res")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(100, 276, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 276, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_pl = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pl.setGeometry(QtCore.QRect(0, 90, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_pl.setFont(font)
        self.pushButton_pl.setStyleSheet("background-color: rgb(85, 85, 0);\n"
"")
        self.pushButton_pl.setObjectName("pushButton_pl")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 214, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 152, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 214, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 152, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 152, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 214, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_min = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_min.setGeometry(QtCore.QRect(300, 152, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_min.setFont(font)
        self.pushButton_min.setStyleSheet("background-color: rgb(85, 85, 0);")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_ym = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ym.setGeometry(QtCore.QRect(100, 90, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_ym.setFont(font)
        self.pushButton_ym.setStyleSheet("background-color: rgb(85, 85, 0);")
        self.pushButton_ym.setObjectName("pushButton_ym")
        self.pushButton_raz = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_raz.setGeometry(QtCore.QRect(200, 90, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_raz.setFont(font)
        self.pushButton_raz.setStyleSheet("background-color: rgb(85, 85, 0);")
        self.pushButton_raz.setObjectName("pushButton_raz")
        self.pushButton_sb = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sb.setGeometry(QtCore.QRect(300, 90, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_sb.setFont(font)
        self.pushButton_sb.setStyleSheet("background-color: rgb(85, 85, 0);")
        self.pushButton_sb.setObjectName("pushButton_sb")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 214, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_rav = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rav.setGeometry(QtCore.QRect(300, 276, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_rav.setFont(font)
        self.pushButton_rav.setStyleSheet("background-color: rgb(85, 85, 0);")
        self.pushButton_rav.setObjectName("pushButton_rav")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 276, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(255, 39, 1);")
        self.pushButton_0.setObjectName("pushButton_0")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.func()

        self.equal = False


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_res.setText(_translate("MainWindow", "0"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_pl.setText(_translate("MainWindow", "+"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_min.setText(_translate("MainWindow", "-"))
        self.pushButton_ym.setText(_translate("MainWindow", "*"))
        self.pushButton_raz.setText(_translate("MainWindow", "/"))
        self.pushButton_sb.setText(_translate("MainWindow", "С"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_rav.setText(_translate("MainWindow", "="))
        self.pushButton_0.setText(_translate("MainWindow", "0"))

    def func(self):
        self.pushButton_0.clicked.connect(lambda: self.write_num(self.pushButton_0.text()))
        self.pushButton_1.clicked.connect(lambda: self.write_num(self.pushButton_1.text()))
        self.pushButton_2.clicked.connect(lambda: self.write_num(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(lambda: self.write_num(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(lambda: self.write_num(self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(lambda: self.write_num(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(lambda: self.write_num(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(lambda: self.write_num(self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(lambda: self.write_num(self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(lambda: self.write_num(self.pushButton_9.text()))
        self.pushButton_pl.clicked.connect(lambda: self.write_num(self.pushButton_pl.text()))
        self.pushButton_min.clicked.connect(lambda: self.write_num(self.pushButton_min.text()))
        self.pushButton_ym.clicked.connect(lambda: self.write_num(self.pushButton_ym.text()))
        self.pushButton_raz.clicked.connect(lambda: self.write_num(self.pushButton_raz.text()))

        self.pushButton_rav.clicked.connect(self.res)
        self.pushButton_sb.clicked.connect(self.delete)

    def write_num(self, num):
        if self.label_res.text() == '0' or self.equal:
            self.label_res.setText(num)
            self.equal = False
        else:
            self.label_res.setText(self.label_res.text() + num)

    def res(self):
        res = str(eval(self.label_res.text()))
        self.label_res.setText(res)
        self.equal = True

    def delete(self):
        self.label_res.setText(self.pushButton_0.text())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
